version: '3.9'

services:
  web:
    build: .
    command: python manage.py
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: